#Crear un workflow que se ejecute cuando se pushea algo en la rama testing
name: push rama testing
on:
  push:
    branches:
    - 'testing'
jobs:
  job01:
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: echo Se acaba de hacer un push en la rama testing
