#Crear un workflow que se ejecute en los minutos pares.
name: Ejecucuión minutos pares
on:
  push:
    branches:
    - 'testing'
  schedule:
    - cron: '*/2 * * * *'
jobs:
  job01:
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: echo Ejecución en los minutos pares
