#Crear un workflow que se ejecute con un formulario en Github, que me pregunte en qué rama quiero ejecutarlo y en qué environment.
name:
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
      branch:
        description: 'Branch to use'
        required: true
        default: 'master'
        type: choice
        options:
        - master
        - develop
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "El workflow se ha ejecutado en la rama: $BRANCH"
          echo "en el enviorment: $ENVIRONMENT"
        env:
          BRANCH: ${{ inputs.branch }}
          ENVIRONMENT: ${{ inputs.environment }}