#Crear un workflow que se ejecute con un botón en Github.
name: Ejecucuión manual
on: workflow_dispatch
jobs:
  job01:
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: echo Ejecución manual
